/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagementsystem;

//import com.mysql.cj.xdevapi.Statement;
//import com.sun.jdi.connect.spi.Connection;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ASUS
 */
public class Product extends javax.swing.JFrame {

    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
        prodTableSelector();
        getCat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        prodIdText = new javax.swing.JTextField();
        prodNameText = new javax.swing.JTextField();
        prodQuantityText = new javax.swing.JTextField();
        prodDescText = new javax.swing.JTextField();
        AddProductBtn = new javax.swing.JButton();
        ProdEditBtn = new javax.swing.JButton();
        deleteProdBtn = new javax.swing.JButton();
        prodHomeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        prodCatCb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCT");

        jLabel2.setText("PRODUCT ID ");

        jLabel3.setText("PRODUCT NAME");

        jLabel4.setText("QUANTITY");

        jLabel5.setText("DESCRIPTION");

        jLabel6.setText("CATEGORY");

        AddProductBtn.setText("ADD");
        AddProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductBtnActionPerformed(evt);
            }
        });

        ProdEditBtn.setText("EDIT");
        ProdEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdEditBtnActionPerformed(evt);
            }
        });

        deleteProdBtn.setText("DELETE");
        deleteProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProdBtnActionPerformed(evt);
            }
        });

        prodHomeBtn.setText("HOME");
        prodHomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodHomeBtnMouseClicked(evt);
            }
        });
        prodHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodHomeBtnActionPerformed(evt);
            }
        });

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT_ID", "PRODUCT_NAME", "QUANTITY", "DESCRIPTION", "CATEGORY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prodCatCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prodDescText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prodQuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prodNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(84, 84, 84)
                            .addComponent(prodIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prodHomeBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddProductBtn)
                                .addGap(63, 63, 63)
                                .addComponent(ProdEditBtn)))
                        .addGap(17, 17, 17)))
                .addGap(59, 59, 59)
                .addComponent(deleteProdBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(prodIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(prodNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(prodQuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(prodDescText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(prodCatCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddProductBtn)
                            .addComponent(ProdEditBtn)
                            .addComponent(deleteProdBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prodHomeBtn)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    Connection con = null;
    Statement stn = null;
    ResultSet Rs = null;
    DbAccess db1 = new DbAccess();
    
    public void prodTableSelector(){
        try{
            con = DriverManager.getConnection(db1.getdbString(), db1.getDbUser(), db1.getDbPass());
            stn = con.createStatement();
            Rs = stn.executeQuery("SELECT * FROM TBL_PRODUCT");
     
            ProductTable.setModel(DbUtils.resultSetToTableModel(Rs));
            
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    private void getCat(){
        try{
            con = DriverManager.getConnection(db1.getdbString(), db1.getDbUser(), db1.getDbPass());
            stn = con.createStatement();
            String query = "SELECT * FROM TBL_CATEGORY";
            Rs = stn.executeQuery(query);
            while(Rs.next()){
                String myCat = Rs.getString("CAT_NAME");
                prodCatCb.addItem(myCat);
            
        }
                    
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }
    
    private void AddProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductBtnActionPerformed
        try{
            con = DriverManager.getConnection(db1.getdbString(), db1.getDbUser(), db1.getDbPass());

            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventoryDB", "user1", "12345");
            PreparedStatement add = con.prepareStatement("INSERT INTO TBL_PRODUCT VALUES (?,?,?,?,?)");
            add.setInt(1, Integer.valueOf(prodIdText.getText()));
            add.setString(2, prodNameText.getText());
            add.setInt(3,Integer.valueOf(prodQuantityText.getText()));
            add.setString(4,prodDescText.getText());
            add.setString(5, prodCatCb.getSelectedItem().toString());
            int row = add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Product has been successfully added.");
            con.close();
            prodTableSelector();
        }catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_AddProductBtnActionPerformed

    private void deleteProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProdBtnActionPerformed
       if(prodIdText.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "Please enter product ID !");
       }
       else{
        try{
            con = DriverManager.getConnection(db1.getdbString(), db1.getDbUser(), db1.getDbPass());
            int id = Integer.valueOf(prodIdText.getText());
            String query  = "DELETE FROM TBL_PRODUCT WHERE PRODUCT_ID = " +id;
            Statement add = con.createStatement();
            add.executeUpdate(query);
            prodTableSelector();
            
            
        }catch(SQLException e){
            e.printStackTrace();
        }
       }
    }//GEN-LAST:event_deleteProdBtnActionPerformed

    private void ProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)ProductTable.getModel();
        int myIndex = ProductTable.getSelectedRow();
        prodIdText.setText(model.getValueAt(myIndex, 0).toString());
        prodNameText.setText(model.getValueAt(myIndex, 1).toString());
        prodQuantityText.setText(model.getValueAt(myIndex, 2).toString());
        prodDescText.setText(model.getValueAt(myIndex, 3).toString());
        //prodCatCb.set(model.getValueAt(myIndex, 4).toString());
        prodCatCb.setSelectedItem(model.getValueAt(myIndex, 4));
    }//GEN-LAST:event_ProductTableMouseClicked

    private void ProdEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdEditBtnActionPerformed
        if(prodIdText.getText().isEmpty() || prodNameText.getText().isEmpty() || prodQuantityText.getText().isEmpty() || prodDescText.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Information");
        }else{
            try{
                 con = DriverManager.getConnection(db1.getdbString(), db1.getDbUser(), db1.getDbPass());
                 String updateQuery = "UPDATE TBL_PRODUCT SET PRODUCT_NAME = '" +prodNameText.getText()+"'"+", PRODUCT_QUANTITY =" +prodQuantityText.getText() + ""+",PRODUCT_DESC = '" +prodDescText.getText()+"'"+",PRODUCT_CATEGORY ='"+prodCatCb.getSelectedItem().toString()+"'"+" WHERE PRODUCT_ID = "+prodIdText.getText();
                 Statement add = con.createStatement();
                 add.executeUpdate(updateQuery);
                 JOptionPane.showMessageDialog(this, "Product has been updated");
                 con.close();
                 prodTableSelector();
            }catch (Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e);
            }
        }
            
    }//GEN-LAST:event_ProdEditBtnActionPerformed

    private void prodHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodHomeBtnActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_prodHomeBtnActionPerformed

    private void prodHomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodHomeBtnMouseClicked
       new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prodHomeBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProductBtn;
    private javax.swing.JButton ProdEditBtn;
    private javax.swing.JTable ProductTable;
    private javax.swing.JButton deleteProdBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> prodCatCb;
    private javax.swing.JTextField prodDescText;
    private javax.swing.JButton prodHomeBtn;
    private javax.swing.JTextField prodIdText;
    private javax.swing.JTextField prodNameText;
    private javax.swing.JTextField prodQuantityText;
    // End of variables declaration//GEN-END:variables
}
